config/routes.rb
Rails.application.routes.draw do
  get 'daily_status_updates/new'
  root 'projects#index'
  resources :tasks
  resources :projects
  devise_for :users
  resources :daily_status_updates
  patch '/tasks/:id/update_status/:type', to: 'tasks#update_status', as: :task_update_status
  get '/report', to: 'report#reporter'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    if user.admin?
       can :manage, :all
    else
      can :manage, Task, user_id: user.id
      can :read, :all
    end
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/daily_status_update.rb
class DailyStatusUpdate < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :users, through: :tasks
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project

  enum status: %i[incomplete started completed]

  validates :description, :due_date, presence: true
  # after_update_status 


  # def methods_name
  #   binding.pry
  # statsus, complted
  #   UserMailer.create_notifivta
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  has_many :projects, through: :tasks
  has_many :daily_status_updates
  after_create :assign_default_role
  enum role: %i[admin employee team_leader project_manager]

  def assign_default_role
    self.role = "employee"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/daily_status_updates_controller.rb
class DailyStatusUpdatesController < ApplicationController
  def new
    @daily_status_update=DailyStatusUpdate.new
  end
  def create
    @daily_status_update=DailyStatusUpdate.new(daily_status_update_params)
   if @daily_status_update.save
      
   end
  end

  private

  def daily_status_update_params
    params.require(:daily_status_update).permit(:to,:status_date,:project,:working_hours,:task,:user_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.includes(:tasks, :users).all # eager loading, N+1 query problem
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.includes(:project, :user).order(created_at: :asc)  end

  # GET /tasks/1 or /tasks/1.json
  def show
    end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @tasks = Task.find(params[:id])
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @tasks = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_status
    @task = Task.find(params[:id])
    @task.update(status: params[:type])
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("status_#{@task.id}", @task.status)
        ]
      end
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @tasks = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:due_date, :description, :user_id, :project_id, :estimated_hours,:spend_hours,:status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def most_projects
    @user = User.most_projects
  end


  def new
    if logged_in
      redirect_to projects_path
      flash[:notice] = "You are already logged in."
    else
      @user = User.new
      render layout: 'sessions'
    end
  end

  def create

    @user = User.new(user_params)

    if @user.save

      session[:user_id] = @user.id
      redirect_to projects_path
    else
      render :new, layout: 'sessions'
    end

  end



  # def show
  #   @user = User.find_by(params[:id])
  #
  #   @tasks = @user.tasks
  # end

  private


  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_status_updates_helper.rb
module DailyStatusUpdatesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/daily_status_updates/new.html.erb
<div class="container">
  <h class="display-6">Send Daily Status Updates</h>
<%= form_for(@daily_status_update) do |f|%>

  <div class="form-row">
     <div class="form-group col-3">
      <%= f.label :to, "Your Reporting Manager Email" %>
      <%= f.text_field :to, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :user_id, "Select the User for this task:" %><br>
      <%= f.collection_select :user_id, User.all, :id, :email %>
    </div>
    <div class="form-group">
      <%= f.label :status_date, "Status Date"%>
      <%= f.date_select :status_date, class: "form-control" %>
    </div>
  </div>


    <div class="form-group col-md-4">
      <%= f.label :project, "Select the Project for this task:" %><br>
      <%= f.collection_select :project, Project.all, :id, :name %>
    </div>
    <div class="form-group col-md-1">
      <%= f.label :working_hours, "Working Hours" %>
      <%= f.time_field :working_hours, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :user_id, "Select the User for this task:" %><br>
      <%= f.collection_select :user_id, User.all, :id, :email %>
    </div>

    <div class="form-group col-7">
      <%= f.label :task, "Task" %>
      <%= f.text_field :task, class: "form-control" %>
    </div><br>

    <div class="actions">
      <%= f.submit "Send", class: "btn btn-success" %>
    </div>
  <% end  %>

 </div>

<p>Find me in app/views/daily_status_updates/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class = "text-center">

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Project Manager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">


          <li class="nav-item">
            <a class="btn btn-outline-success" href="<%= new_task_path %>">Create New Task</a>
          </li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Attendance
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/daily_status_updates/new">Daily Status</a></li>

          </ul>
        </li>

            <li class="nav-item">
            <a class="nav-link" href="<%= projects_path%>">Home</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="<%= new_project_path %>">Create New Project</a>
          </li>



          <li class="nav-item">
            <a class="nav-link" href="/tasks">All Tasks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/report">Report</a>
          </li>

          <li >
            <%=button_to "logout", destroy_user_session_path,method: :delete %>
          </li>


        </ul>
      </div>
    </nav>


    <%= yield %>

  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
 
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">

  <div >
 <% @projects.each do |project| %>
     <h2>  <%= link_to project.name, project%></h2>
     <% tasks = project.tasks %>

     <%= render partial: 'tasks/tasklist', :locals => {:@tasks => tasks}%>

  <% end %>
</div>
</div>
<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@task.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<br>
<div class="container">
  <%= form_for(@task) do |f| %>
    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_field :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :due_date, "Due date"%>
      <%= f.date_select :due_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :project_id, "Select the Project for this task:" %><br>
      <%= f.collection_select :project_id, Project.all, :id, :name %>
    </div>
    <div class="form-group">
      <%= f.label :user_id, "Select the User for this task:" %><br>
      <%= f.collection_select :user_id, User.all, :id, :email %>
    </div>
    <div class="form-group">
      <%= f.label :estimated_hours, "estimated hours" %>
      <%= f.number_field :estimated_hours, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :spend_hours, "spend hours" %>
      <%= f.number_field :spend_hours, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :status %><br>
      <%= f.select :status, Task.statuses.keys.collect{|k,v| [k.titleize, k]} %>
     </div>
    <div class="actions">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end  %>
</div>
<div>

</div>

app/views/tasks/_tasklist.html.erb
<table class = "table table-striped" >
  <thead class = "thead-dark">
    <tr class="text-bg-warning">
      <th scope="col">id</th>
      <th scope="col">Task</th>
      <th scope="col">Project</th>
      <th scope="col">Due Date </th>
      <th scope="col">Assigned To</th>
      <th scope="col">Edit/Delete</th>
      <th scope="col">Estimated hours</th>
      <th scope="col">Spend hours</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= link_to task.description,tasks_path %></td>
        <td> <%= task.project.name %> </td>
        <td> <%= task.due_date.strftime("%B %d, %Y") unless task.due_date.nil?  %> </td>
        <td> <%= task.user.email  %> </td>
        <td> <% if can? :update, task%>
        <%= link_to "Edit", edit_task_path(task) %>
         /<%end%> <%=  button_to 'Delete', task, method: :delete %> </td>
        <td> <%= task.estimated_hours  %> </td>
        <td> <%= task.spend_hours  %> </td>
        <td>
          <div id="status_<%= task.id %>">
            <%= task.status %>
          </div>
          <div>
            <% Task.statuses.keys.each do |status|%>
              <%= button_to status.capitalize, task_update_status_path(task.id, status), method: :patch, class: 'btn btn-outline-danger'%>
            <%end%>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>


    <div class="container">
      <%= render 'tasklist', :locals => {:@tasks => @tasks} %>
      </div>







<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>
Action was success
<div>

  <%= link_to "Edit this task", edit_task_path(@task) %>|
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/tasks/update_status.html.erb
gbbdxvcvc

app/views/users/index.html.erb
you are authorized

app/views/users/new.html.erb
<br>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<br>

<div class="container">


<%= form_for @user , :html => {class: "form-signin"} do |f| %>

  <div class="form-group">
    <%= f.label :email, "E-mail" %>
    <%= f.text_field :email, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :username, "Username" %>
    <%= f.text_field :username, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :password, "Password"%>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field  :password_confirmation , class: "form-control"%>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up", class: "btn btn-primary" %>
  </div>

  <% end %>


</div>